These notebooks are based on code provided by Robert Johansson - [Numerical Python - A Practical Techniques Approach for Industry](http://www.apress.com/9781484205549) (ISBN 978-1-484205-54-9).

# Chapter 2: Vectors, matrices and multidimensional arrays

Vectors, matrices, and arrays of higher dimensions are essential tools in numerical
computing. When a computation must be repeated for a set of input values, it is natural
and advantageous to represent the data as arrays and the computation in terms of
array operations. Computations that are formulated this way are said to be vectorized.

Vectorized computations can
therefore be significantly faster than sequential element-by-element computations. This
is particularly important in an interpreted language such as Python, where looping over
arrays element by element entails a significant performance overhead.

In Python’s scientific computing environment, efficient data structures for working
with arrays are provided by the `NumPy` library. The core of NumPy is implemented in C
and provides efficient functions for manipulating and processing arrays.

## Importing the Modules

In order to use the NumPy library, we need to import it in our program. By convention,
the numPy module imported under the alias `np`.

In [3]:
import numpy as np

## The NumPy array object

The main data structure for multidimensional arrays in `NumPy` is the `ndarray` class. In addition to the data stored in the array, this data structure also
contains important metadata about the array, such as its shape, size, data type, and other
attributes.

A full list of
attributes with descriptions is available in the `ndarray docstring`.

In [4]:
np.ndarray?


The following example demonstrates how these attributes are accessed for an
instance data of the class ndarray:

In [5]:
data = np.array([[1, 2], [3, 4], [5, 6]])

In [6]:
# datatype of data variable
type(data)

numpy.ndarray

In [7]:
# value of data variable
data

array([[1, 2],
       [3, 4],
       [5, 6]])

In [8]:
# Number of dimensions (axes).
data.ndim

2

In [9]:
# A tuple that contains the number of elements (i.e., the length) for each dimension (axis) of the array.
data.shape

(3, 2)

In [10]:
# The total number elements in the array.
data.size

6

In [11]:
# The data type of the elements in the array.
data.dtype

dtype('int64')

In [12]:
# Number of bytes used to store the data.
data.nbytes

48

## Data types

The dtype attribute of the ndarray object describes the `data type` of each element in the array (remember, since NumPy
arrays are homogeneous, all elements have the same data type).

In [14]:
# int are int8, int16, int32, int64  (Integers)
np.array([1, 2, 3], dtype=np.int8)

array([1, 2, 3], dtype=int8)

In [15]:
# uint are uint8, uint16, uint32, uint64 (Unsigned (nonnegative) integers)
np.array([1, 2, 3], dtype=np.uint8)

array([1, 2, 3], dtype=uint8)

In [23]:
# bool is bool_ (Boolean (True or False))
np.array([1, 2, 3], dtype=np.bool_)

array([ True,  True,  True])

In [24]:
# float are float16, float32, float64, float128 (Floating-point numbers)
np.array([1, 2, 3], dtype=np.float16)

array([1., 2., 3.], dtype=float16)

In [25]:
# complex are complex64, complex128, complex256 (Complex-valued floating-point numbers)
np.array([1, 2, 3], dtype=np.complex64)

array([1.+0.j, 2.+0.j, 3.+0.j], dtype=complex64)

Once a NumPy array is created, its `dtype` cannot be changed, other than by creating
a new copy with type-casted array values. Typecasting an array is straightforward and
can be done using either the `np.array` function

In [26]:
# Initializing a variable using np.array with dtype function
data = np.array([1, 2, 3], dtype=np.float16)

In [19]:
data

array([1., 2., 3.], dtype=float16)

In [20]:
data.dtype

dtype('float16')

In [27]:
# Typecasting using np.array with dtype function
data = np.array([1, 2, 3], dtype=np.int8)

In [28]:
data.dtype

dtype('int8')

In [29]:
data

array([1, 2, 3], dtype=int8)

Or typecasting by using the `astype` method of the ndarray class

In [31]:
# Initializing a variable using np.array with dtype function
data = np.array([1, 2, 3], dtype=np.float32)

In [32]:
data

array([1., 2., 3.], dtype=float32)

In [34]:
#Typecasting using astype method
data.astype(np.int8)

array([1, 2, 3], dtype=int8)

When computing with NumPy arrays, the data type might get promoted from one
type to another, if required by the operation.

In [35]:
d1 = np.array([1, 2, 3], dtype=float)

In [36]:
d2 = np.array([1, 2, 3], dtype=complex)

In [37]:
d1 + d2

array([2.+0.j, 4.+0.j, 6.+0.j])

In [38]:
(d1 + d2).dtype

dtype('complex128')

In some cases, depending on the application and its requirements, it is essential to
create arrays with data type appropriately set to, for example, `int` or `complex`. The default
type is `float`.

In [39]:
np.sqrt(np.array([-1, 0, 1]))

<ipython-input-39-18cc2be45d00>:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(np.array([-1, 0, 1]))


array([nan,  0.,  1.])

In [40]:
np.sqrt(np.array([-1, 0, 1], dtype=complex))

array([0.+1.j, 0.+0.j, 1.+0.j])

Using the `np.sqrt` function to compute the square root of each element in
an array gives different results depending on the data type of the array. Only when the
data type of the array is complex is the square root of –1 resulting in the imaginary unit
(denoted as 1.j in Python).

### Real and imaginary parts

Regardless of the value of the dtype attribute, all NumPy array instances have the attributes
`real` and `imag` for extracting the real and imaginary parts of the array.

The same functionality is also provided by the functions `np.real` and `np.imag`,
which also can be applied to other array-like objects, such as Python lists.

In [41]:
data = np.array([1, 2, 3], dtype=complex)

In [42]:
data

array([1.+0.j, 2.+0.j, 3.+0.j])

In [43]:
data.real

array([1., 2., 3.])

In [44]:
data.imag

array([0., 0., 0.])

In [45]:
np.real(data)

array([1., 2., 3.])

In [47]:
np.imag(data)

array([0., 0., 0.])

## Creating arrays

Arrays can be generated in a number of ways, depending on their properties and
the applications they are used for.

### Arrays created from lists and other array-like objects

This method is obviously limited
to small arrays. In many situations it is necessary to generate arrays with elements that
follow some given rule, such as filled with constant values, increasing integers, uniformly
spaced numbers, random numbers, etc. In other cases we might need to create arrays
from data stored in a file.


Using the `np.array` function, NumPy arrays can be constructed from explicit Python
lists, iterable expressions, and other array-like objects (such as other ndarray instances)

In [48]:
# to create a one-dimensional array from a Python list
np.array([1, 2, 3, 4])

array([1, 2, 3, 4])

In [49]:
data.ndim

1

In [50]:
data.shape

(3,)

In [54]:
# To create a two-dimensional array with the same data as in the previous
# example, we can use a nested Python list:
data2=np.array([[1, 2], [3, 4]])

In [55]:
data2.ndim

2

In [56]:
data2.shape

(2, 2)

### Arrays filled with constant values

In [ ]:
np.zeros((2, 3))

In [ ]:
np.ones(4)

In [ ]:
data = np.ones(4)

In [ ]:
data.dtype

In [ ]:
data = np.ones(4, dtype=np.int64)

In [ ]:
data.dtype

In [ ]:
x1 = 5.4 * np.ones(10)

In [ ]:
x2 = np.full(10, 5.4)

In [ ]:
x1 = np.empty(5)

In [ ]:
x1.fill(3.0)

In [ ]:
x1

In [ ]:
x2 = np.full(5, 3.0)

In [ ]:
x2

### Arrays filled with incremental sequences

In [ ]:
np.arange(0.0, 10, 1)

In [ ]:
np.linspace(0, 10, 11)

### Arrays filled with logarithmic sequences

In [ ]:
np.logspace(0, 2, 5)  # 5 data points between 10**0=1 to 10**2=100

### Mesh-grid arrays

In [ ]:
x = np.array([-1, 0, 1])

In [ ]:
y = np.array([-2, 0, 2])

In [ ]:
X, Y = np.meshgrid(x, y)

In [ ]:
X

In [ ]:
Y

In [ ]:
Z = (X + Y) ** 2

In [ ]:
Z

### Creating uninitialized arrays

In [ ]:
np.empty(3, dtype=np.float)

### Creating arrays with properties of other arrays

In [ ]:
def f(x):
    y = np.ones_like(x)
    # compute with x and y
    return y

### Creating matrix arrays

In [ ]:
np.identity(4)

In [ ]:
np.eye(3, k=1)

In [ ]:
np.eye(3, k=-1)

In [ ]:
np.diag(np.arange(0, 20, 5))

## Index and slicing

### One-dimensional arrays

In [ ]:
a = np.arange(0, 11)

In [ ]:
a

In [ ]:
a[0]  # the first element

In [ ]:
a[-1] # the last element

In [ ]:
a[4]  # the fifth element, at index 4

In [ ]:
a[1:-1]

In [ ]:
a[1:-1:2]

In [ ]:
a[:5]

In [ ]:
a[-5:]

In [ ]:
a[::-2]


## Multidimensional arrays

In [ ]:
f = lambda m, n: n + 10 * m

In [ ]:
A = np.fromfunction(f, (6, 6), dtype=int)

In [ ]:
A

In [ ]:
A[:, 1]  # the second column

In [ ]:
A[1, :]  # the second row

In [ ]:
A[:3, :3]  # upper half diagonal block matrix

In [ ]:
A[3:, :3]  # lower left off-diagonal block matrix

In [ ]:
A[::2, ::2]  # every second element starting from 0, 0

In [ ]:
A[1::2, 1::3]  # every second element starting from 1, 1

### Views

In [ ]:
B = A[1:5, 1:5]

In [ ]:
B

In [ ]:
B[:, :] = 0

In [ ]:
A

In [ ]:
C = B[1:3, 1:3].copy()

In [ ]:
C

In [ ]:
C[:, :] = 1  # this does not affect B since C is a copy of the view B[1:3, 1:3]

In [ ]:
C

In [ ]:
B

### Fancy indexing and Boolean-valued indexing

In [ ]:
A = np.linspace(0, 1, 11)

In [ ]:
A[np.array([0, 2, 4])]

In [ ]:
A[[0, 2, 4]]

In [ ]:
A > 0.5

In [ ]:
A[A > 0.5]

In [ ]:
A = np.arange(10)

In [ ]:
A

In [ ]:
indices = [2, 4, 6]

In [ ]:
B = A[indices]

In [ ]:
B[0] = -1  # this does not affect A

In [ ]:
A

In [ ]:
A[indices] = -1

In [ ]:
A

In [ ]:
A = np.arange(10)

In [ ]:
B = A[A > 5]

In [ ]:
B[0] = -1  # this does not affect A

In [ ]:
A

In [ ]:
A[A > 5] = -1

In [ ]:
A

## Reshaping and resizing

In [ ]:
data = np.array([[1, 2], [3, 4]])

In [ ]:
np.reshape(data, (1, 4))

In [ ]:
data.reshape(4)

In [ ]:
data = np.array([[1, 2], [3, 4]])

In [ ]:
data

In [ ]:
data.flatten()

In [ ]:
data.flatten().shape

In [ ]:
data = np.arange(0, 5)

In [ ]:
column = data[:, np.newaxis]

In [ ]:
column

In [ ]:
row = data[np.newaxis, :]

In [ ]:
row

In [ ]:
data = np.arange(5)

In [ ]:
data

In [ ]:
np.vstack((data, data, data))

In [ ]:
data = np.arange(5)

In [ ]:
data

In [ ]:
np.hstack((data, data, data))

In [ ]:
data = data[:, np.newaxis]

In [ ]:
np.hstack((data, data, data))

## Vectorized expressions

### Arithmetic operations

In [ ]:
x = np.array([[1, 2], [3, 4]])

In [ ]:
y = np.array([[5, 6], [7, 8]])

In [ ]:
x + y

In [ ]:
y - x

In [ ]:
x * y

In [ ]:
y / x

In [ ]:
x * 2

In [ ]:
2 ** x

In [ ]:
y / 2

In [ ]:
(y / 2).dtype

In [ ]:
x = np.array([1, 2, 3, 4]).reshape(2,2)

In [ ]:
z = np.array([1, 2, 3, 4])

In [ ]:
x / z

In [ ]:
z = np.array([[2, 4]])

In [ ]:
z

In [ ]:
z.shape

In [ ]:
x / z

In [ ]:
zz = np.concatenate([z, z], axis=0)

In [ ]:
zz

In [ ]:
x / zz

In [ ]:
z = np.array([[2], [4]])

In [ ]:
z.shape

In [ ]:
x / z

In [ ]:
zz = np.concatenate([z, z], axis=1)

In [ ]:
zz

In [ ]:
x / zz

In [ ]:
x = np.array([[1, 3], [2, 4]])
x = x + y
x

In [ ]:
x = np.array([[1, 3], [2, 4]])
x += y
x

### Elementwise functions

In [ ]:
x = np.linspace(-1, 1, 11)

In [ ]:
x

In [ ]:
y = np.sin(np.pi * x)

In [ ]:
np.round(y, decimals=4)

In [ ]:
np.add(np.sin(x) ** 2, np.cos(x) ** 2)

In [ ]:
np.sin(x) ** 2 + np.cos(x) ** 2

In [ ]:
def heaviside(x):
    return 1 if x > 0 else 0

In [ ]:
heaviside(-1)

In [ ]:
heaviside(1.5)

In [ ]:
x = np.linspace(-5, 5, 11)

In [ ]:
heaviside(x)

In [ ]:
heaviside = np.vectorize(heaviside)

In [ ]:
heaviside(x)

In [ ]:
def heaviside(x):
    return 1.0 * (x > 0)

### Aggregate functions

In [ ]:
data = np.random.normal(size=(15,15))

In [ ]:
np.mean(data)

In [ ]:
data.mean()

In [ ]:
data = np.random.normal(size=(5, 10, 15))

In [ ]:
data.sum(axis=0).shape

In [ ]:
data.sum(axis=(0, 2)).shape

In [ ]:
data.sum()

In [ ]:
data = np.arange(1,10).reshape(3,3)

In [ ]:
data

In [ ]:
data.sum()

In [ ]:
data.sum(axis=0)

In [ ]:
data.sum(axis=1)

### Boolean arrays and conditional expressions

In [ ]:
a = np.array([1, 2, 3, 4])

In [ ]:
b = np.array([4, 3, 2, 1])

In [ ]:
a < b

In [ ]:
np.all(a < b)

In [ ]:
np.any(a < b)

In [ ]:
if np.all(a < b):
    print("All elements in a are smaller than their corresponding element in b")
elif np.any(a < b):
    print("Some elements in a are smaller than their corresponding elemment in b")
else:
    print("All elements in b are smaller than their corresponding element in a")

In [ ]:
x = np.array([-2, -1, 0, 1, 2])

In [ ]:
x > 0

In [ ]:
1 * (x > 0)

In [ ]:
x * (x > 0)

In [ ]:
def pulse(x, position, height, width):
    return height * (x >= position) * (x <= (position + width))

In [ ]:
x = np.linspace(-5, 5, 11)

In [ ]:
pulse(x, position=-2, height=1, width=5)

In [ ]:
pulse(x, position=1, height=1, width=5)

In [ ]:
def pulse(x, position, height, width):
    return height * np.logical_and(x >= position, x <= (position + width))

In [ ]:
x = np.linspace(-4, 4, 9)

In [ ]:
np.where(x < 0, x**2, x**3)

In [ ]:
np.select([x < -1, x < 2, x >= 2],
          [x**2  , x**3 , x**4])

In [ ]:
np.choose([0, 0, 0, 1, 1, 1, 2, 2, 2],
          [x**2,    x**3,    x**4])

In [ ]:
x[abs(x) > 2]

In [ ]:
np.nonzero(abs(x) > 2)

In [ ]:
x[np.nonzero(abs(x) > 2)]

# Set operations

In [ ]:
a = np.unique([1,2,3,3])

In [ ]:
b = np.unique([2,3,4,4,5,6,5])

In [ ]:
np.in1d(a, b)

In [ ]:
1 in a

In [ ]:
1 in b

In [ ]:
np.all(np.in1d(a, b))

In [ ]:
np.union1d(a, b)

In [ ]:
np.intersect1d(a, b)

In [ ]:
np.setdiff1d(a, b)

In [ ]:
np.setdiff1d(b, a)

### Operations on arrays

In [ ]:
data = np.arange(9).reshape(3, 3)

In [ ]:
data

In [ ]:
np.transpose(data)

In [ ]:
data = np.random.randn(1, 2, 3, 4, 5)

In [ ]:
data.shape

In [ ]:
data.T.shape

## Matrix and vector operations

In [ ]:
A = np.arange(1, 7).reshape(2, 3)

In [ ]:
A

In [ ]:
B = np.arange(1, 7).reshape(3, 2)

In [ ]:
B

In [ ]:
np.dot(A, B)

In [ ]:
np.dot(B, A)

In [ ]:
A = np.arange(9).reshape(3, 3)

In [ ]:
A

In [ ]:
x = np.arange(3)

In [ ]:
x

In [ ]:
np.dot(A, x)

In [ ]:
A.dot(x)

In [ ]:
A = np.random.rand(3,3)
B = np.random.rand(3,3)

In [ ]:
Ap = B @ A @ np.linalg.inv(B)
Ap

In [ ]:
Ap = np.dot(B, np.dot(A, np.linalg.inv(B)))
Ap

In [ ]:
Ap = B.dot(A.dot(np.linalg.inv(B)))
Ap

In [ ]:
A = np.matrix(A)

In [ ]:
B = np.matrix(B)

In [ ]:
Ap = B * A * B.I

In [ ]:
A = np.asmatrix(A)

In [ ]:
B = np.asmatrix(B)

In [ ]:
Ap = B * A * B.I

In [ ]:
Ap = np.asarray(Ap)

In [ ]:
Ap

In [ ]:
np.inner(x, x)

In [ ]:
np.dot(x, x)

In [ ]:
y = x[:, np.newaxis]

In [ ]:
y

In [ ]:
np.dot(y.T, y)

In [ ]:
x = np.array([1, 2, 3])

In [ ]:
np.outer(x, x)

In [ ]:
np.kron(x, x)

In [ ]:
np.kron(x[:, np.newaxis], x[np.newaxis, :])

In [ ]:
np.kron(np.ones((2,2)), np.identity(2))

In [ ]:
np.kron(np.identity(2), np.ones((2,2)))

In [ ]:
x = np.array([1, 2, 3, 4])

In [ ]:
y = np.array([5, 6, 7, 8])

In [ ]:
np.einsum("n,n", x, y)

In [ ]:
np.inner(x, y)

In [ ]:
A = np.arange(9).reshape(3, 3)

In [ ]:
B = A.T

In [ ]:
np.einsum("mk,kn", A, B)

In [ ]:
np.alltrue(np.einsum("mk,kn", A, B) == np.dot(A, B))

# Versions

In [ ]:
%reload_ext version_information
%version_information numpy